### ISSUE TITLE
make menuconfig fails

### ISSUE THREAD

**Issue by p1ersson** [hubaiz/DslrDashboardServer#14]
With a fresh clone i fail to do a 'make menuconfig':
 
~/src/packages/DslrDashboardServer $ make menuconfig                                                                        
Makefile:5: /rules.mk: No such file or directory
Makefile:13: /package.mk: No such file or directory
make: *** No rule to make target `/package.mk'.  Stop.

**Comment by p1ersson** [comment]
bah, that was tad bit short' eh? I tried make on a Linux Mint (Petra)-host.

**Comment by hubaiz** [comment]
Hi

For ddserver there is no 'make menuconfig'

Just 'make' that will compile ddserver

'make menuconfig' is used to configure OpenWrt when building it.

Zoltan

**Comment by p1ersson** [comment]
dyxlectic user
