### ISSUE TITLE
Error opening USB imaging device: -3

### ISSUE THREAD

**Issue by ThomasH-W** [hubaiz/DslrDashboardServer#21]
I can control a Nikon D7000 when connecting to a Windows-PC with the qDslrDashboard.
It is also possible to release the shutter using an arduino connected to the Nikon.

Now when running the DDserver on a rapsberry Pi0 w with Jessie, I do get error mentioned  in the title.
Where should I go from here ?

As a reference: here is the syslog:

Mar  9 18:44:30 DSLRpi0 kernel: [ 4680.736956] usb 1-1: new high-speed USB device number 9 using dwc_otg
Mar  9 18:44:30 DSLRpi0 kernel: [ 4680.737327] Indeed it is in host mode hprt0 = 00001101
Mar  9 18:44:30 DSLRpi0 kernel: [ 4680.937743] usb 1-1: New USB device found, idVendor=04b0, idProduct=0428
Mar  9 18:44:30 DSLRpi0 kernel: [ 4680.937771] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Mar  9 18:44:30 DSLRpi0 kernel: [ 4680.937783] usb 1-1: Product: NIKON DSC D7000
Mar  9 18:44:30 DSLRpi0 kernel: [ 4680.937794] usb 1-1: Manufacturer: NIKON
Mar  9 18:44:30 DSLRpi0 kernel: [ 4680.937804] usb 1-1: SerialNumber: 000006311502

Mar  9 18:39:11 DSLRpi0 ddserver: Starting socket server on port 4757
Mar  9 18:39:11 DSLRpi0 ddserver: Awaiting client connection
Mar  9 18:39:11 DSLRpi0 ddserver: Starting UDP listener
Mar  9 18:39:11 DSLRpi0 ddserver: join multicast group: 224.1.2.3
Mar  9 18:39:18 DSLRpi0 ddserver: Incoming client connection
Mar  9 18:39:18 DSLRpi0 ddserver: Awaiting client connection
Mar  9 18:39:18 DSLRpi0 ddserver: USB Devices in
Mar  9 18:39:18 DSLRpi0 ddserver: Number of possible configurations: 1 Device Class: 0 VendorID: 1200, ProductID: 1064
Mar  9 18:39:18 DSLRpi0 ddserver: Number of alternate settings:
Mar  9 18:39:18 DSLRpi0 ddserver: Interface class: 6 Interface number: 0 Number of endpoints: 3
Mar  9 18:39:18 DSLRpi0 ddserver: Found USB imaging device, get vendor and product
**Mar  9 18:39:18 DSLRpi0 ddserver: Error opening USB imaging device: -3**
Mar  9 18:39:18 DSLRpi0 ddserver: Number of possible configurations: 1 Device Class: 9 VendorID: 7531, ProductID: 2
Mar  9 18:39:18 DSLRpi0 ddserver: Number of alternate settings:
Mar  9 18:39:18 DSLRpi0 ddserver: Interface class: 9 Interface number: 0 Number of endpoints: 1
Mar  9 18:39:18 DSLRpi0 ddserver: Imaging USB devices found: 0
Mar  9 18:39:18 DSLRpi0 ddserver: Error reading total packet size: 0
Mar  9 18:39:18 DSLRpi0 ddserver: Stoping client
Mar  9 18:39:20 DSLRpi0 ddserver: Closing USB device

**Comment by hubaiz** [comment]
I guess that ddserver can't access the USB device as it is probably automatically mounted by the system.

**Comment by ThomasH-W** [comment]
Just found the solution: need to start the ddserver as root:
 sudo ./ddserver
Probably worth of adding this to the installation guide.
