### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by parkerlreed** [hubaiz/DslrDashboardServer#29]
Working great here on a battery powered router. 
![IMG_20190502_235527](https://user-images.githubusercontent.com/841440/57119377-b17e8b00-6d37-11e9-9765-ef0ae1194b8e.jpg)

**Comment by hubaiz** [comment]
:)

**Comment by parkerlreed** [comment]
Action shot! Interface is taking a lot of getting used to but really loving it overall. 

![IMG_9593](https://user-images.githubusercontent.com/841440/57336306-7099c400-70f3-11e9-9779-a4ef70217e13.JPG)
