### ISSUE TITLE
Compiling package for TL-WR902AC v3

### ISSUE THREAD

**Issue by mati97** [hubaiz/DslrDashboardServer#41]
Hi,

I've been trying to compile this library for two days now without any success. Would you be so kind and please compile it for MediaTek MT7610EN?🙏

**Comment by hubaiz** [comment]
You should compile for the MT7628AN
https://openwrt.org/toh/tp-link/tl-wr902ac_v3
![image](https://github.com/hubaiz/DslrDashboardServer/assets/1691871/478c2585-bb32-4b10-8559-5e270143cb42)

Also try with my latest commit.

**Comment by mati97** [comment]
I got to this point, I even compiled it and tried to install it, but then it says it doesn't have uclibcxx. When I try to install it, I don't have gcc and enough space on router to compile it and it seems like endless spiral of trouble ;D

**Comment by mati97** [comment]
I'm sorry, there has been a mistake in my op. I did compile for MT7628AN.
