### ISSUE TITLE
your server versus usb over ip http://usbip.sourceforge.net/

### ISSUE THREAD

**Issue by mobiphil** [hubaiz/DslrDashboardServer#9]
Hi,

was glad to find your project as I am both interested in photography and hacking.
I wonder if there were any reason to write your server, instead of using the usb over ip

http://usbip.sourceforge.net/

mobi phil

**Comment by hubaiz** [comment]
Hi

I only needed a proxy server for PTP not a full USB device. There also no
drivers for Android as far I know and also none for iOS.

Zoltan

**Comment by mobiphil** [comment]
Indeed, did not think about this important detail: android/ios are the clients for usb over ethernet the virtual VHCI driver is missing.
